# Generated by Django 3.1.2 on 2022-09-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220927_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(through='articles.ArticleTags', to='articles.Tags'),
        ),
    ]
