# Generated by Django 3.1.2 on 2022-09-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletags',
            old_name='tags',
            new_name='scope',
        ),
        migrations.RemoveField(
            model_name='article',
            name='scope',
        ),
    ]
