# Generated by Django 3.1.2 on 2022-09-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220928_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(through='articles.ArticleTags', to='articles.Tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(through='articles.ArticleTags', to='articles.Article'),
        ),
    ]
