# Generated by Django 3.1.2 on 2022-09-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220928_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletags',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tags'),
        ),
    ]
